<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BuscarHotelesControlador;
use App\Http\Controllers\DescubreEspanaControlador;
use App\Http\Controllers\OlvidoPasswordControlador;
use App\Http\Controllers\RealizarReservaControlador;
use App\Http\Controllers\InformacionUsuarioControlador;
use App\Http\Controllers\EditarPerfilControlador;
use App\Http\Controllers\ResenasControlador;
use App\Http\Controllers\ReservasControlador;
use App\Http\Controllers\PanelRecepcionistaControlador;
use App\Http\Controllers\ListarReservasControlador;
use App\Http\Controllers\ListadoCheckoutControlador;
use App\Http\Controllers\ListadoCheckinControlador;
use App\Http\Controllers\ListarUsuariosControlador;
use App\Http\Controllers\ListarServiciosControlador;
use App\Http\Controllers\ListarHotelesControlador;
use App\Http\Controllers\ListarHabitacionesControlador;

Route::get('/user', function (Request $request) {
    return $request->user();
})->middleware('auth:sanctum');

Route::get('/buscar-hoteles', [BuscarHotelesControlador::class, 'buscarhoteles'])->name('api.buscarHoteles');
Route::get('/descubreEspana/{ciudad}', [DescubreEspanaControlador::class, 'descubreEspana'])->name('api.descubreEspana');
Route::post('/olvido-password', [OlvidoPasswordControlador::class, 'olvidoPassword'])->name('api.olvidoPassword');
Route::get('/realizarreserva', [RealizarReservaControlador::class, 'realizarreserva'])->name('api.realizarreserva');
Route::post('/guardarreserva', [RealizarReservaControlador::class, 'guardarreserva'])->name('api.guardarreserva');
Route::get('/informacionusuario/{id}', [InformacionUsuarioControlador::class, 'mostrarinformacion'])->name('api.informacionusuario');
Route::get('/editarperfil/{clienteID}', [EditarPerfilControlador::class, 'mostrarPerfil'])->name('api.editarperfil');
Route::post('/editarperfil/{clienteID}/{id}', [EditarPerfilControlador::class, 'editarPerfil'])->name('api.editarPerfil');
Route::get('/dejarresena/{clienteID}', [ResenasControlador::class, 'dejarResenas'])->name('api.dejarResenas');
Route::post('/escribirresena/{hotelID}', [ResenasControlador::class, 'guardarResena'])->name('api.guardarResena');
Route::get('/mostrarresena/{clienteID}', [ResenasControlador::class, 'mostrarResenas'])->name('api.mostrarResenas');
Route::get('/misreservas/{clienteID}', [ReservasControlador::class, 'mostrarMisReservas'])->name('api.mostrarMisReservas');
Route::get('/listarreservas', [ListarReservasControlador::class, 'listarReservas'])->name('api.listarReservas');
Route::delete('/delreserva/{reservaID}', [ListarReservasControlador::class, 'delReserva'])->name('api.delReserva');
Route::get('/mostrarreserva/{reservaID}', [ListarReservasControlador::class, 'mostrarReserva'])->name('api.mostrarReserva');
Route::put('/editarreserva/{reservaID}', [ListarReservasControlador::class, 'editarReserva'])->name('api.editarReserva');
Route::get('/listadocheckout', [ListadoCheckoutControlador::class, 'listadoCheckout'])->name('api.listadoCheckout');
Route::get('/mostrarcheckout/{reservaID}', [ListadoCheckoutControlador::class, 'mostrarCheckout'])->name('api.mostrarCheckout');
Route::put('/registrarcheckout/{reservaID}', [ListadoCheckoutControlador::class, 'registrarCheckout'])->name('api.registrarCheckout');
Route::get('/listadocheckin', [ListadoCheckinControlador::class, 'listadoCheckin'])->name('api.listadoCheckin');
Route::get('/mostrarcheckin/{reservaID}', [ListadoCheckinControlador::class, 'mostrarCheckin'])->name('api.mostrarCheckin');
Route::put('/registrarcheckin/{reservaID}', [ListadoCheckinControlador::class, 'registrarCheckin'])->name('api.registrarCheckin');
Route::get('/listarservicios', [ListarServiciosControlador::class, 'listarServicios'])->name('api.listarServicios');
Route::delete('/delservicio/{servicioID}', [ListarServiciosControlador::class, 'delServicio'])->name('api.delServicio');
Route::get('/mostrarservicio/{servicioID}', [ListarServiciosControlador::class, 'mostrarServicio'])->name('api.mostrarServicio');
Route::put('/editarservicio/{servicioID}', [ListarServiciosControlador::class, 'editarServicio'])->name('api.editarServicio');
Route::get('/anadir-servicio', [ListarServiciosControlador::class, 'anadirServicio'])->name('api.anadirServicio');
Route::post('/guardarservicio', [ListarServiciosControlador::class, 'guardarServicio'])->name('api.guardarServicio');
Route::get('/gestionarhoteles', [ListarHotelesControlador::class, 'listarHoteles'])->name('api.listarHoteles');
Route::delete('/delhotel/{hotelID}', [ListarHotelesControlador::class, 'delHotel'])->name('api.delHotel');
Route::get('/mostrarhotel/{hotelID}', [ListarHotelesControlador::class, 'mostrarHotel'])->name('api.mostrarHotel');
Route::put('/editarhotel/{hotelID}', [ListarHotelesControlador::class, 'editarHotel'])->name('api.editarHotel');
Route::get('/mostrar-hoteles', [ListarHotelesControlador::class, 'mostrarHoteles'])->name('api.mostrarHoteles');
Route::post('/anadir-hoteles', [ListarHotelesControlador::class, 'anadirHotel'])->name('api.anadirHotel');
Route::get('/gestionarhabitaciones', [ListarHabitacionesControlador::class, 'listarHabitaciones'])->name('api.listarHabitaciones');
Route::delete('/delhabitacion/{habitacionID}', [ListarHabitacionesControlador::class, 'delHabitacion'])->name('api.delHabitacion');
Route::get('/mostrar-habitaciones', [ListarHabitacionesControlador::class, 'mostrarHabitaciones'])->name('api.mostrarHabitaciones');
Route::post('/anadir-habitaciones', [ListarHabitacionesControlador::class, 'anadirHabitacion'])->name('api.anadirHabitacion');
Route::get('/mostrarhabitacion/{habitacionID}', [ListarHabitacionesControlador::class, 'mostrarHabitacion'])->name('api.mostrarHabitacion');
Route::put('/editarhabitacion/{habitacionID}', [ListarHabitacionesControlador::class, 'editarHabitacion'])->name('api.editarHabitacion');
Route::get('/listarusuarios', [ListarUsuariosControlador::class, 'listarUsuarios'])->name('api.listarUsuarios');
Route::delete('/delusuario/{id}', [ListarUsuariosControlador::class, 'delUsuario'])->name('api.delUsuario');
Route::get('/mostrarusuario/{id}', [ListarUsuariosControlador::class, 'mostrarUsuario'])->name('api.mostrarUsuario');
Route::put('/editarusuario/{id}', [ListarUsuariosControlador::class, 'editarUsuario'])->name('api.editarUsuario');
Route::get('/mostrar-usuarios', [ListarUsuariosControlador::class, 'mostrarUsuarios'])->name('api.mostrarUsuarios');
Route::post('/anadir-usuarios', [ListarUsuariosControlador::class, 'anadirUsuario'])->name('api.anadirUsuario');